### PR TITLE
Modified code for the whole of the Bristol dataset

### PR DESCRIPTION
**Pull request by pevans13**
Added the resulting matched and unmatched species

### CODE REVIEW

**Comment by pevans13** [comment]
@philipmwheeler, @tdjames1, I have modified the code and run it with the whole Bristol dataset. Seems to work, only not matching things liked 'mixed species' and species that are not on the original species list

**Comment by tdjames1** [comment]
Hi @pevans13, have you committed and pushed the complete .Rmd file? I can only see the first few lines of the file here!

**Comment by pevans13** [comment]
I thought I had. I’ve have to try again when I get home this evening.

Paul

**Comment by pevans13** [comment]
Full script should be visible now @tdjames1

**Comment by philipmwheeler** [comment]
Thanks Paul. Your code matched a few more than my original! Interesting to note that a common unmatched taxon based on this code is Leyland cypress, scientific/botanical name: x Cupressocyparis leylandii. I think this doesn't match because it's unusual in the 'x' appearing first in the name.

**Comment by philipmwheeler** [comment]
A thought on this - the matching is an improvement, but it's very slow. My original approach was to extract unique 'species' and then match these. This reduces the number of things that need matching from the tens of thousands to the hundreds and then replace 'species' in the original data frame based on this, so a lot quicker.

**Comment by philipmwheeler** [comment]
Further observation - for some reason Liquidamber [sic] isn't matched/corrected to Liquidambar

**Comment by tdjames1** [comment]
@philipmwheeler A first pass that picks up direct matches would be sensible. Also it might be possible to do further matching without using the string splitting function but instead doing regular expression based pattern matching. I'm not sure how much that goes back to your original approach!

**Pull request merged**
